Edited lss - added exit conditions

diff --git a/lss b/lss
--- a/lss
+++ b/lss
@@ -4,23 +4,34 @@
 # Date: 13/05/2013
 # Description: Use git to retrieve various Linux Configuration files from a repository on github.
 #+++++++++++++++++++++
-# Files:
-#       .bashrc
-#       .bash_aliases
-#       .vimrc
-#       .Xresources
-# Dirs:
+#       ~/.bashrc
+#       ~/.bash_aliases
+#       ~/.vimrc
+#       ~/.Xresources
 #       ~/.vim/
 #+++++++++++++++++++++
 # This script runs from ~/bin - create the directory if it doesn't exist or modify the file to reflect where you want your scripts folder e.g. ~/scripts, /usr/bin
 
-# Exit if the repo doesn't exist.
-# git verify command here
-if [ $? -eq 0 ]; then
-  echo "The LSS git already exists, skipping this part."
+if eval "ping -c 1 www.google.com > /dev/null"; then
+  :
 else
-  printf "Cannot be run in this fashion run the following command first:\ngit clone git@github.com:iseijin/LSS.git ~/bin/LSS"
-  exit 32
+  echo "No Internet Connection. Aborting."
+  exit 1
+fi
+
+# Test if git is installed
+command -v git >/dev/null 2>&1 || { echo >&2 "I require git but it's not installed.  Aborting."; exit 1;  }
+
+# git verify command here
+
+if [ $? -eq 0 ]; then
+  echo "The LSS git already exists, continuing..."
+else  
+  self_delete=true # Delete this file as the real copy will be retrieved with git
+  printf "This script cannot be run without the Git repo, the following command will be run first:\ngit clone git@github.com:iseijin/LSS.git ~/bin/LSS"
+  git clone git@github.com:iseijin/LSS.git ~/bin/LSS
+  
+
 fi
 
 # Create sym links to files in LSS/configFiles
@@ -47,4 +58,8 @@ fi
 if [ ! -L ~/.vim ]; then
   echo "Creating link for ~/.vim"
   ln -s ~/bin/LSS/configFiles/.vim ~/.vim
+fi
+
+if $self_delete; then
+  rm $0
 fi
